In [1]:
distance = [10, 15, 17, 26, 20]
times = [0.3, 0.47, 0.55, 1.2, 1.0]

In [2]:
speeds = []
for i in range(len(distance)):
    speeds.append(distance[i]/times[i])
    
print(speeds)

[33.333333333333336, 31.914893617021278, 30.909090909090907, 21.666666666666668, 20.0]


In [3]:
product_quantities = [13, 5, 6, 10, 11]
prices = [1.2, 3.2, 1, 4.5, 6]

In [4]:
pip install numpy

You should consider upgrading via the 'D:\Anaconda\python.exe -m pip install --upgrade pip' command.


In [5]:
import numpy as np
print(np.__version__)

1.18.5


In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
dis = np.array(distance)
time = np.array(times)

print(dis/time)

[33.33333333 31.91489362 30.90909091 21.66666667 20.        ]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)

(3, 3)


In [10]:
arr = np.zeros((2, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
arr = np.ones((4, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
import numpy as np
arr = np.random.randn(3, 4)
print(arr*100)

[[  84.25918839  -69.1876616    26.76326476  189.98744433]
 [ -69.85002065    9.74584786    5.70461946  -16.32368636]
 [ -64.77503898  130.27665582  -74.09748747 -128.79107544]]


# Indexing and Slicing

In [14]:
arr[1]

array([-0.69850021,  0.09745848,  0.05704619, -0.16323686])

In [15]:
arr = np.arange(12).reshape(2, 2, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [16]:
arr[-1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
arr = np.arange(10)
print(arr)
print(arr[5:])

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [18]:
print(arr[:-5])

[0 1 2 3 4]


In [19]:
arr = np.arange(18).reshape(3, 2, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [23]:
arr[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
arr[0:2:]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [27]:
arr[1,:,1]

array([ 7, 10])

In [28]:
arr[:, 1, 1]

array([ 4, 10, 16])

In [40]:
arr[..., 2]

array([[ 2,  5],
       [ 8, 11],
       [14, 17]])

# Boolean Indexing

In [48]:
cities = np.array(["delhi", "banglore","mumbai", "chennai", "bhopal"])
city_data = np.random.randn(5, 3)
city_data

array([[-0.71749207,  2.37640105, -0.91550745],
       [ 0.16826641, -0.53068937, -1.97550943],
       [ 0.95291314, -1.39835824, -1.12790807],
       [-0.77001407,  0.04098591,  0.80112337],
       [ 0.13049516, -0.64389858, -2.13768064]])

In [49]:
city_data[cities == "mumbai"]

array([[ 0.95291314, -1.39835824, -1.12790807]])

In [50]:
print(cities=="mumbai")

[False False  True False False]


In [51]:
city_data[cities == "bombay"]

array([], shape=(0, 3), dtype=float64)

In [52]:
city_data[city_data>0]

array([2.37640105, 0.16826641, 0.95291314, 0.04098591, 0.80112337,
       0.13049516])

In [53]:
city_data[city_data<0] = 0
city_data

array([[0.        , 2.37640105, 0.        ],
       [0.16826641, 0.        , 0.        ],
       [0.95291314, 0.        , 0.        ],
       [0.        , 0.04098591, 0.80112337],
       [0.13049516, 0.        , 0.        ]])

In [55]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [58]:
arr1 = np.arange(15).reshape(5, 3)
arr2 = np.arange(5).reshape(5, 1)
arr2 + arr1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [69]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

In [70]:
A.dot(B)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [71]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])